#!/bin/bash
#
# The "commit-msg" hook is run just before "git commit" starts doing its job, and can prevent the
# command from running by exiting with non-zero status.
#
# Details:
# Enforce commit conventions by verify the commit log message. The hook is allowed to edit the
# commit message file.
#
# Arguments:
#   $1 - the name of the file that has the commit message
#
# Returns:
#   Exitcode

# -x: print a trace (debug)
# -u: treat unset variables
# -o pipefail: return value of a pipeline
set -uo pipefail

# Include libraries

. ./scripts/utils/log.sh
. ./scripts/utils/fs.sh
. ./scripts/utils/git.sh
. ./scripts/utils/hook.sh

# Constant variables

COMMIT_MESSAGE_FILE="${1}"
readonly COMMIT_MESSAGE_FILE

LOG_FILE="$(git_root_dir)/logs/githooks/commit-msg.log"
readonly LOG_FILE

# Internal functions

run_commit_msg() {
  local -i retval=0

  fs_create_file "${LOG_FILE}"

  hook_verify_commit_convention "make run-linter-commit" "${COMMIT_MESSAGE_FILE}" &>"${LOG_FILE}"
  ((retval = $?))
  if ((retval != 0)); then
    log_message "githooks" "pre-push" "${retval}"

    return "${retval}"
  fi

  # fs_remove_file "${LOG_FILE}"

  return "${retval}"
}

# Control flow logic

run_commit_msg
exit "${?}"
