#!/bin/bash
#
# Enforce code style guides via linters.

# -x: print a trace (debug)
# -u: treat unset variables
# -o pipefail: return value of a pipeline
set -uo pipefail

# Include libraries

. ./scripts/utils/log.sh
. ./scripts/utils/fs.sh
. ./scripts/utils/git.sh
. ./scripts/utils/hook.sh

# Constant variables

LOG_FILE="$(git_get_root_dir)/logs/githooks/pre-commit.log"
readonly LOG_FILE

# Internal functions

run_pre_commit() {
  local -i result=0

  fs_create_file "${LOG_FILE}"

  hook_enforce_coding_standards "make run-linter-staged" &>"${LOG_FILE}"
  ((result = $?))
  if ((result == 1)); then
    log_monitor "githooks" "pre-push" "${result}"

    return "${result}"
  fi

  fs_remove_file "${LOG_FILE}"

  return "${result}"
}

# Control flow logic

run_pre_commit
exit "${?}"
