---
trigger: none
pool:
  vmImage: ubuntu-22.04
resources:
  repositories:
    - repository: self
      persistCredentials: true
stages:
  - stage: continuous_security
    jobs:
      - job: continuous_security
        displayName: Continuous Security
        timeoutInMinutes: 15
        steps:
          - task: Bash@3
            displayName: Setup Security
            inputs:
              targetType: inline
              script: |
                make setup-continuous-security
          - task: Bash@3
            displayName: Run Security
            continueOnError: true
            inputs:
              targetType: inline
              script: |
                make run-continuous-security
          - task: CopyFiles@2
            displayName: Upload Artifacts
            inputs:
              contents: "logs/**"
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            displayName: Publish Artifacts
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: continuous-security-artifact
