---
# NOTE Pull Request (PR) triggers are implemented in Azure Repos Git using branch policies.
# E.g. Repos > Branches > main > Branch Policies > Build Validation
# See https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&tabs=browser#build-validation
trigger: none
pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: self
      persistCredentials: true
stages:
  - stage: continuous_security
    jobs:
      - job: continuous_security
        displayName: Continuous Security
        timeoutInMinutes: 5
        steps:
          - task: Bash@3
            displayName: Display Contributor
            inputs:
              targetType: inline
              script: |
                echo Build.RequestedForId : $(Build.RequestedForId)
                echo Build.RequestedForEmail : $(Build.RequestedForEmail)
                echo Build.RequestedFor : $(Build.RequestedFor)
                echo Build.SourceVersionAuthor : $(Build.SourceVersionAuthor)
                echo Build.SourceVersion : $(Build.SourceVersion)
                echo Build.DefinitionName : $(Build.DefinitionName)
                echo Build.Reason : $(Build.Reason)
                echo System.TeamProject : $(System.TeamProject)
          - task: Bash@3
            displayName: Verify Contributor
            inputs:
              targetType: inline
              script: if [[ "$(Build.RequestedFor)" != "$(Build.SourceVersionAuthor)" ]] ; then exit 1; fi
