---
trigger: none
pool:
  vmImage: ubuntu-latest
resources:
  pipelines:
    - pipeline: Continuous Security
      source: continuous-security
      trigger:
        enabled: true
stages:
  - stage: continuous_integration
    jobs:
      - job: continuous_integration
        displayName: Continuous Integration
        timeoutInMinutes: 15
        steps:
          - task: Bash@3
            displayName: Setup Integration
            inputs:
              targetType: inline
              script: |
                make setup-continuous-integration
          - task: Bash@3
            displayName: Run Integration
            inputs:
              targetType: inline
              script: |
                make run-continuous-integration
          - task: CopyFiles@2
            displayName: Upload Artifacts
            inputs:
              contents: "logs/*/*.log"
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            displayName: Publish Artifacts
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: continuous-integration-artifact
