---
- name: Install Package Managers
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present

    - name: Install Go
      ansible.builtin.apt:
        name: golang
        state: present
      vars:
        go_version: 1.20.5
      environment:
        PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
        GOPATH: $HOME/go
