---
- name: Import Playbook
  ansible.builtin.import_playbook: install-go.yml

- name: Install Package Managers
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true
      become: true

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present
        update_cache: true
      become: true
