---
name: Continuous Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: continuous-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Release
        run: |
          make setup-continuous-release
      - name: Run Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN  }}
        run: |
          make run-continuous-release
