---
name: Continuous-Security
on:
  pull_request:
    branches:
      - main
jobs:
  security:
    if: ${{ github.event_name == 'pull_request' }}
    name: continuous-security
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Setup Security
        run: |
          make setup-continuous-security
      - name: Run Security
        run: |
          make run-continuous-security
      - name: Upload Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: continuous-security-artifact
          path: logs/**/*.log
